### ISSUE TITLE
Allow CoherenceCluster crd to override dnsPolicy and enable hostNetwork in statefulsets

### ISSUE THREAD

**Issue by jtyl2017** [oracle/coherence-operator#365]
Corporate policy may restrict the creation of Kubernetes Services that are of type: LoadBalancer. and as a result, external traffic to kubernetes coherence cluster nodes will be blocked. To allow external traffic access (in cases such as management and extend role nodes), we will need to apply the following workaround. 

We will need the ability to set:
- dnsPolicy=ClusterFirstWithHostNet 
- hostNetwork=true
- per role annotations
via the CoherenceCluster crd yaml file.

e.g. Sample content in CoherenceCluster crd yaml file (see ### <<---)
```
apiVersion: v1
items:
- apiVersion: coherence.oracle.com/v1
  kind: CoherenceCluster
  metadata:
    ...
  spec:
    application:
      ...
    coherence:
      ...
    env:
    ...
    roles:
    - application:
      role: proxy
      network:                              ### <<--- network section
        annotations:                        ### <<--- role specific annotations section
          dns.alpha.kubernetes.io/internal: ### <<--- role specific management coherence url here
        dnsPolicy: ClusterFirstWithHostNet  ### <<--- Chosen DNS Policy here
        hostNetwork:                        ### <<--- Enable HostNetwork
          enabled: true                     ### <<--- Enable HostNetwork
```

Once the CoherenceCluster crd yaml with above additions are deployed, the:
- selected dnsPolicy, 
- hostNetwork enabled
- dns annotations (role specific)
settings should be applied to resulting Kubernetes Statefulsets and pods created by the CoherenceCluster crd. 

e.g. Sample Result from CoherenceCluster crd yaml spec file (see ### <<---)
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  ...
  labels:
    ...
  name: ...
spec:
  ...
  template:
    metadata:
      annotations:                        ### <<-- role specific annotations section
        dns.alpha.kubernetes.io/internal: ### <<--- role specific management coherence url here
        prometheus.io/port: "2408"
    spec:
      ...
      containers:
        ...
      dnsPolicy: ClusterFirstWithHostNet  ### <<--- DNS Policy chosen
      hostNetwork: true                   ### <<--- hostNetwork enabled
```
