### ISSUE TITLE
Coherence Pods fail to start on OpenShift

### ISSUE THREAD

**Issue by thegridman** [oracle/coherence-operator#379]
When deploying a Coherence cluster on OpenShift using the Operator the Coherence Pods fail to start.

The `yaml` used to create the cluster is:
```
apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
 name: cluster1
spec:
 imagePullSecrets:
  - name: oracle-store-secret
```
The `coherence-k8s-utils` init-container crashes with the following log output:
```
[root@openshift bin]# kubectl logs cluster1-storage-0 -c coherence-k8s-utils -p
Starting container initialisation
Creating target directories under /utils
Copying files to /utils
Copying files/*.sh to /utils/scripts
Copying directory /files to /utils/scripts
Copying files/*.jar to /utils/lib
Copying directory /files to /utils/lib
Copied file /files/coherence-utils.jar to /utils/lib/coherence-utils.jar
Copied file /files/opendmk_jmxremote_optional_jar.jar to /utils/lib/opendmk_jmxremote_optional_jar.jar
Copying copy utility
Copied file /files/copy to /utils/copy
Copying op-test utility
Copied file /files/op-test to /utils/op-test
Creating directory /snapshot
panic: mkdir /snapshot: permission denied
goroutine 1 [running]:
main.main()
	/scratch/cohbld/hudson/workspace/coherence-operator-nightly/cmd/utilsinit/main.go:97 +0xab4
```

This would appear to be a permissions problem where the init-container user cannot create `/snapshot` when using OpenShift.
