### ISSUE TITLE
Deployment of a new release is "stuck" due to a missing image

### ISSUE THREAD

**Issue by rbair23** [oracle/coherence-operator#464]
For some reason, my rollout got stuck on one pod during upgrade (the coherence.yaml had the wrong image version). After replacing the coherence descriptor, I expected to see the stateful set get updated and the pods replaced with ones with the right image version, but this did not happen.

➜ kubectl --context iotiad_inf_dp -n rbair-sim get pods                                              
NAME                            READY   STATUS             RESTARTS   AGE
microservice-hosted-sim-api-0   1/1     Running            0          7d1h
microservice-hosted-sim-api-1   1/1     Running            0          7d1h
microservice-hosted-sim-api-2   0/1     ImagePullBackOff   0          2m20s

➜ kubectl --context iotiad_inf_dp -n rbair-sim get coherence                                         
NAME                          CLUSTER                       ROLE                          REPLICAS   READY   PHASE
microservice-hosted-sim-api   microservice-hosted-sim-api   microservice-hosted-sim-api   3          2       RollingUpgrade

The image to be used in `microservice-hostd-sim-api` was `iad.ocir.io/iotdev/hosted-sim-api-server:1.0.2`. However, when I looked into my pod that wasn’t starting it was trying to start with the old (non-existent) `image iad.ocir.io/iotdev/hosted-sim-api-server:1.1`. If I delete the pod, it comes back still trying to start `iad.ocir.io/iotdev/hosted-sim-api-server:1.1`. I looked into the stateful set, and I could see it referred to the old version number. By deleting the stateful set, the Coherence Operator replaced it and then things started up correctly.

**Comment by thegridman** [comment]
I have been unable to recreate this issue. I know we do have a similar issue where the Operator gets stuck but I cannot see it in the scenario you describe.

The steps I took to recreate this were:
1. Deploy a three member cluster with an image that exists.
```
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: test-one
spec:
  replicas: 3
  image: ghcr.io/oracle/operator-test:3.1.2
  cluster: test-cluster
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
```
2. All three Pods came up fine.
```
NAME             READY   STATUS    RESTARTS   AGE
pod/test-one-0   1/1     Running   0          35s
pod/test-one-1   1/1     Running   0          35s
pod/test-one-2   1/1     Running   0          35s
```
3. Update the `Coherence` yaml to have an image name that does not exist and re-apply with `kubectl apply`
```
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: test-one
spec:
  replicas: 3
  image: ghcr.io/oracle/operator-test-foo:3.1.2
  cluster: test-cluster
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
```
4. The `StatefulSet` spec is updated by the Operator and the `StatefulSet` proceeds to do a rolling upgrade.
5. The first Pod to be upgraded eventually gets stuck in `ImagePullBackOff`
```
NAME             READY   STATUS             RESTARTS   AGE
pod/test-one-0   1/1     Running            0          100s
pod/test-one-1   1/1     Running            0          100s
pod/test-one-2   0/1     ImagePullBackOff   0          47s
```
6. Change the `Coherence` yaml back to the original with an existing image and re-apply
7. The Pods then come back to running

Maybe I have misunderstood your specific scenario. Also I'm doing this with the latest Operator 3.1.1.
